lib/platform_web/router.ex
defmodule PlatformWeb.Router do
  use PlatformWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlatformWeb.UserNamePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :basic_auth do
    if Mix.env == :prod do
      plug PlatformWeb.BasicAuthPlug, username: "timer", password: "timer"
    end
  end

  scope "/", PlatformWeb do
    pipe_through [:browser, :basic_auth] # Use the default browser stack

    get "/", PageController, :index

    resources "/user", UserController, singleton: true
    resources "/rooms", RoomController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlatformWeb do
  #   pipe_through :api
  # end
end

lib/platform/core/room.ex
defmodule Platform.Core.Room do
  @moduledoc """
  The Room Schema.
  """

  @derive {Phoenix.Param, key: :uuid}
  defstruct [
    :name,
    :uuid,
    :image
  ]

end

lib/platform_web/controllers/room_controller.ex
defmodule PlatformWeb.RoomController do
  use PlatformWeb, :controller

  alias Platform.Core

  def index(conn, _params) do
    rooms = Core.list_rooms()

    render(conn, "index.html", rooms: rooms)
  end

  def show(conn, %{"id" => id}) do
    room = Core.get_room!(id)

    render(conn, "show.html", room: room)
  end
end

lib/platform_web/views/room_view.ex
defmodule PlatformWeb.RoomView do
  use PlatformWeb, :view
end

lib/platform_web/templates/room/index.html.eex
<h2>Listing Rooms</h2>

Hallo <%= @conn.cookies["user_name"] %> (<%= link "Change name", to: user_path(@conn, :show) %>)
<div data-room-uuid="lobby"></div>
<div>
  Current users in the lobby: <span id="presence_users"></span>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Users</th>
    </tr>
  </thead>
  <tbody>
<%= for room <- @rooms do %>
    <tr>
      <td><%= link room.name, to: room_path(@conn, :show, room) %></td>
      <td data-show-users-in-room="room:<%= room.uuid %>"><%= Platform.Presence.list("room:#{room.uuid}") |> Map.keys |> Enum.join(", ") %></td>
    </tr>
<% end %>
  </tbody>
</table>

lib/platform_web/templates/room/show.html.eex
<!-- Metadata for JS ATM via this element-data -->
<div data-room-uuid="<%= @room.uuid %>"></div>

<div class="position-absolute-fullscreen background-image-fullscreen"
style="background-image: url(<%= static_path(@conn, "/images/rooms/#{@room.image} ") %>);">

</div>
<div class="position-absolute-fullscreen text-white">
  <div class="d-flex flex-column h-100">
    <div class="room-header">
      <div class="d-flex">
        <span class="h1 pt-5 mx-auto">
          <%= @room.name %>
        </span>
      </div>
    </div>
    <div class="room-center m-auto">
      <div class="d-flex flex-column">
        <!-- <div class="mode-buttons">
            <button id="set-counter-to-pomodoro">Pomodoro</button>
            <button id="set-counter-to-short-break">Short Break</button>
            <button id="set-counter-to-long-break">Long Break</button>
        </div> -->
        <div class="d-flex">
          <span class="m-auto text-light h1">
            <%= link "≣", to: room_path(@conn, :index), class: "text-light" %>
          </span>
        </div>
        <div class="m-auto">
          <div class="d-flex rounded-circle rounded-circle-200px bg-dark">
            <span id="counter" class="m-auto h1"></span>
          </div>
        </div>
        <div class="buttons pt-3">
          <button class="btn btn-success" id="start-counter">Start</button>
          <button class="btn btn-danger" id="stop-counter">Stop</button>
          <button class="btn btn-secondary" id="reset-counter">Reset</button>
        </div>
      </div>
    </div>
    <div class="room-footer">
      <div class="text-white p-3 bg-info">
        Current users in this room:
        <span id="presence_users"></span>
      </div>
    </div>
  </div>
</div>